config/routes.rb
Rails.application.routes.draw do

  get 'answers/index'

  get 'answers/new'

  get 'answers/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
          :controllers => {:invitations => 'users_invitations'}# user_invitations_controller.rb



  authenticate :user, ->(user) { user.student? } do
    root 'student_dashboard#index'
    resources :students, only: [:edit, :update]
  end

  authenticate :user, ->(user) { user.lecturer? } do
    root 'lecturer_dashboard#index'
    resources :lecturers, only: [:edit, :update]
  end
  resources :subjects do
    resources :materials, only: [:new, :create]
    resources :assignments, only: [:new, :create]
    resources :announcements, only: [:new, :create]
  end
  resources :student_subjects do
    resources :materials, only: [:new, :create]
    resources :assignments, only: [:new, :create]
    resources :announcements, only: [:new, :create]
  end
  resources :lecturer_subjects do
    resources :materials, only: [:new, :create]
    resources :assignments, only: [:new, :create]
    resources :announcements, only: [:new, :create]
  end
  resources :lecturer_subjects
  resources :student_subjects
  resources :courses do
    resources :subjects
  end

  resources :assignments do
    resources :answers
  end

  # resources :conversations, only: [:create] do
  #   member do
  #     post :close
  #   end
  #   resources :messages, only: [:create]
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/announcement.rb
class Announcement < Upload

  belongs_to :subject

end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :assignment
	belongs_to :student

	mount_uploader :attachment, AttachmentUploader
end

app/models/assignment.rb
class Assignment < Upload

  belongs_to :subject
  has_many :answers

end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :subjects
	has_many :lecturers
	has_many :students

	#accepts_nested_attributes_for :subjects
end

app/models/lecturer.rb
class Lecturer < User

  belongs_to :course
  has_many :lecturer_subjects
  has_many :subjects, through: :lecturer_subjects
  has_many :lecturer_students
  has_many :students, through: :lecturer_students
  has_many :materials
  has_many :announcements
  has_many :assignments
  # has_many :uploads
end

app/models/lecturer_subject.rb
class LecturerSubject < ApplicationRecord
  belongs_to :lecturer
  belongs_to :subject
end

app/models/material.rb
class Material < Upload

  belongs_to :subject

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/student.rb
class Student < User
  has_many :lecturer_students
  has_many :lecturers, through: :lecturer_students
  has_many :student_subjects
  has_many :subjects, through: :student_subjects
  has_many :answers
end

app/models/student_subject.rb
class StudentSubject < ApplicationRecord

	belongs_to :student
	belongs_to :subject
	# has_many :assignments
	# has_many :materials
	# has_many :announcements
	# # validates :title, presence: true

 #    # def self.all_subject_titles
 #    #  all.map(&:title)
 #    # end
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :lecturer_subjects
	has_many :lecturer, through: :lecturer_subjects
	has_many :uploads
	belongs_to :course
	has_many :student_subjects
	has_many :students, through: :student_subjects
	has_many :assignments
	has_many :announcements
	has_many :materials
	enum student_class: [:computing, :networking, :multimedia, :bba]

	def self.all_subject_titles
     all.map(&:title)
    end
end

app/models/upload.rb
class Upload < ApplicationRecord

  belongs_to :subject
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

         has_many :uploads
         has_many :messages
         has_many :conversations, foreign_key: :sender_id

  def student?
    type == 'Student'
  end

  def lecturer?
    type == 'Lecturer'
  end

end

app/controllers/lecturer_subjects_controller.rb
class LecturerSubjectsController < ApplicationController
  def index
    @lecturer = current_user
    @lecturer_subjects = LecturerSubject.all
  end

  def show
    @lecturer_subject = LecturerSubject.find(params[:id])
    @materials = @lecturer_subject.subject.materials
    @assignments = @lecturer_subject.subject.assignments
    @announcements = @lecturer_subject.subject.announcements
  end

  def new
    @subject = current_user.subjects.new
  end

  def create
    subjects = params[:lecturer_subject][:lecturer_id].map.with_index{|v,i| v  unless i == 0}.compact
    subjects.each do |subject|
      sub = Subject.find_by_title(subject)
      current_user.lecturer_subjects.find_or_create_by(subject_id: sub.id)
    end
    redirect_to root_url
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/lecturer_subjects_controllers.rb
class LecturerSubjectController < ApplicationController
  def index
    @subjects = Subjects.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = current_user.subjects.new
  end

  def create
    @subject = current_user.subjects.new
    if @subject.save
      redirect_to2s
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lecturer_subject_helper.rb
module LecturerSubjectHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lecturer_subjects/_form.html.erb
<%= form_for :lecturer_subject, url: lecturer_subjects_path, html: { multipart: true } do |f| %>
<div>
  <div class= "well", style="width:50%; height: 300px; margin: 0 auto; text-align:center; margin-top:100px;">
    <h3>Select Subject</h3>
    <%= f.label :Subjects%>
    <%= f.select :lecturer_id, Subject.all_subject_titles, {}, multiple: true, class: 'customSelect form-control chosen-select', data: { placeholder: "Select Subject"}, style:"width:50%; height:40px;" %>
    <div class="subject-button" style="margin-top: 40px;">
      <%= f.submit "Save Subject", class: "btn btn-info" %>
    </div>
  </div></br>
  <div class="actions">
    
  </div>
<% end %>
</div>

app/views/lecturer_subjects/create.html.erb
<h1>LecturerSubject#create</h1>
<p>Find me in app/views/lecturer_subject/create.html.erb</p>

app/views/lecturer_subjects/destroy.html.erb
<h1>LecturerSubject#destroy</h1>
<p>Find me in app/views/lecturer_subject/destroy.html.erb</p>

app/views/lecturer_subjects/edit.html.erb
<h1>LecturerSubject#edit</h1>
<p>Find me in app/views/lecturer_subject/edit.html.erb</p>

app/views/lecturer_subjects/index.html.erb
<div class="student-subjects">
  <div class="well">
    <% @subjects.each do |subject| %>
    <ul class="well" style="background-color: #ffffff;">
      <li><%= link_to "#{subject.title}", student_subjects_path%></li>
    </ul>

    <% end %>
  </div>
</div>

app/views/lecturer_subjects/new.html.erb
<%= render  "form"%>

app/views/lecturer_subjects/show.html.erb
<!--  
<head>
  <title>Bootstr</title>
  <<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<div class="container" style="width: 100%; padding-left: 60px; padding-right:  60px">

        <%= image_tag "subjectbg.jpg", class: "subimg" %>

    <div class="container">

      <ul class="nav nav-tabs" style="position: relative;top: 0;bottom: 0;left: 0;right: 0;margin-top: 211px;margin-left: 445px;">
        <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
        <li><a data-toggle="tab" href="#menu1">Study Materials</a></li>

        <%= link_to "Post Assignment", new_lecturer_subject_assignment_path(@lecturer_subject), class: "btn btn-success"%>
        <%= link_to "Post Announcement", new_lecturer_subject_announcement_path(@lecturer_subject), class: "btn btn-success"%>
        <%= link_to "Post Materials", new_lecturer_subject_material_path(@lecturer_subject), class: "btn btn-success"%>
      </ul>


        <div class="tab-content" style="padding-top:240px;">
            <div id="home" class="tab-pane fade in active">
            <%@assignments.each do |assignment|%>
              <div class="panel panel-default">
                <div class="panel-heading">Assignment_<%= assignment.title %> 
                  <div style="float:right;"> Due Date_<%= assignment.try(:submission_end_date).try(:strftime, "%d/%m/%Y")%></div>
                </div>
                  <div class="panel-body"><%= link_to "#{assignment.attachment}", assignment.attachment_url, target: "blank"%></div>
                  </div>
                <%end%>
            </div>

            <div class="tab-content" style="padding-top:240px;">
            <div id="Study Materials" class="tab-pane fade in active">
            <% @announcements.each do |announcement|%>
              <div class="panel panel-default">
                <div class="panel-heading">Announcement !!!<%= announcement.title %></div>
                  <div class="panel-body"><%= announcement.description%></div>
                  </div>
                <%end%>
            </div>
        <div id="menu1" class="tab-pane fade">
          <div class="tab-content" style="padding-top:240px;">
            <div id="home" class="tab-pane fade in active">
            <% @materials.each do |material|%>
              <div class="panel panel-default">
                <div class="panel-heading">Study Material <%= material.title %></div>
                  <div class="panel-body"><%= link_to "#{material.title}"%></div>
                  </div>
                <%end%>
            </div> 
        </div>
        <div id="menu2" class="tab-pane fade">
          <h3>Menu 2</h3>
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
        </div>
        <div id="menu3" class="tab-pane fade">
          <h3>Menu 3</h3>
          <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
        </div>
      </div>
    </div>
 </div>
</html> -->












<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<%= image_tag "subjectbg.jpg", class: "subimg" %>

<div class="assignmentdesc" style="position: relative; text-align: center;">
  <h2>Title :</h2>
  <h1>code :</h1>
</div>

<body>

<div class="container">
<tabs>
  <ul class="nav nav-tabs" style="margin-bottom: 10px; margin-top: 40px;">
        <li class="active"><a data-toggle="tab" href="#menu1">Assignment</a></li>
        <li><a data-toggle="tab" href="#menu2">Announcement</a></li>
        <li><a data-toggle="tab" href="#menu3">Study Materials</a></li>
        <li><a data-toggle="tab" href="#menu4">Answers</a></li>

      <ul class="nav nav-tabs pull-right"> 
         <%= link_to "Post Assignment", new_lecturer_subject_assignment_path(@lecturer_subject), class: "btn btn-success"%>
        <%= link_to "Post Announcement", new_lecturer_subject_announcement_path(@lecturer_subject), class: "btn btn-success"%>
        <%= link_to "Post Materials", new_lecturer_subject_material_path(@lecturer_subject), class: "btn btn-success"%>        
      </ul>
  </ul>
</tabs>

  <div class="tab-content">
    <div id="menu1" class="tab-pane fade in active">
            <%@assignments.each do |assignment|%>
              <div class="panel panel-default">
                <div class="panel-heading">Assignment_<%= assignment.title %> 
                    <div style="float:right;"> Due Date_<%= assignment.try(:submission_end_date).try(:strftime, "%d/%m/%Y")%>
                    </div>
                </div>
                <div class="panel-body"><%= link_to "#{assignment.attachment}", assignment.attachment_url, target: "blank"%>
                </div>
              </div>
            <%end%>
    </div>

    <div id="menu2" class="tab-pane fade">
              <% @announcements.each do |announcement|%>
          <div class="panel panel-default">
              <div class="panel-heading">Announcement !!!<%= announcement.title %></div>
              <div class="panel-body"><%= announcement.description%></div>
              <%end%>
          </div>
    </div>

    <div id="menu3" class="tab-pane fade">
            <% @materials.each do |material|%>
              <div class="panel panel-default">
                <div class="panel-heading">Study Material <%= material.title %></div>
                  <div class="panel-body"><%= link_to "#{material.title}"%></div>
                  </div>
            <%end%>
    </div>

    <div id="menu4" class="tab-pane fade">
            


            
    </div>

  </div>
</div>

</body>
</html>

app/views/lecturer_subjects/update.html.erb
<h1>LecturerSubject#update</h1>
<p>Find me in app/views/lecturer_subject/update.html.erb</p>